Auth/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from Auth import views

urlpatterns = [
    path('register/', views.RegisterFormView.as_view()),
    path('login/', auth_views.LoginView.as_view(template_name='login.html', redirect_authenticated_user=True),
         name='user_login'),
    path('logout/', auth_views.LogoutView.as_view())
]

Core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import DetailView, ListView, RedirectView

from Core.models import Archive, CostCategory, HelpText, ShoppingList, ShoppingListItem, VersionControl
from Core.views import actions, views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_tools/', include('admin_tools.urls')),
    path('', RedirectView.as_view(url='/panel/')),
    path('favicon.ico', RedirectView.as_view(url='/static/image/favicon.ico'), name='favicon'),
    path('panel/', views.BaseTemplateView.as_view(template_name='panel/base.html'), name='panel'),
    path('panel/home/', views.BaseTemplateView.as_view(template_name='panel/panel.html')),
    path('panel/new/', views.BaseTemplateView.as_view(template_name='panel/new.html')),
    path('panel/about/', views.TemplateView.as_view(template_name='panel/about.html')),
    path('panel/help/', ListView.as_view(template_name='panel/help.html', model=HelpText)),
    path('panel/version/', ListView.as_view(template_name='panel/version.html', model=VersionControl)),
    path('panel/new_version/', ListView.as_view(template_name='panel/version.html', model=VersionControl)),
    path('panel/archive/', views.ArchiveTemplateView.as_view(template_name='panel/archive/archive.html')),
    path('<name>/', views.BaseTemplatePlanView.as_view(template_name='plan/base.html'), name='base'),
    path('<name>/home/', views.BaseTemplatePlanView.as_view(template_name='plan/home.html')),
    path('<name>/cost/', views.CostTemplatePlanView.as_view(template_name='plan/cost.html')),
    path('<name>/stat/', views.StatTemplatePlanView.as_view(template_name='plan/stat/stat.html')),
    path('<name>/shopping_list/',
         views.ShoppingListTemplateView.as_view(template_name='plan/shopping_list/shopping_list.html')),
    path('<name>/shopping_list/<id>/',
         views.DetailShoppingListTemplateView.as_view(template_name='plan/shopping_list/create_shopping_list.html')),
    path('<name>/settings/', views.BaseTemplatePlanView.as_view(template_name='plan/settings.html')),
    path('<name>/archive/', views.ArchiveTemplatePlanView.as_view(template_name='plan/archive/archive.html')),
    path('<name>/archive/<date_one>/<date_two>/',
         views.ArchiveReportLastPeriodView.as_view(template_name='plan/archive/report_last_period.html')),
    path('<name>/archive/<type_date>/', views.GetDatesInArchive.as_view()),
    path('archive/detail/<int:pk>/',
         DetailView.as_view(template_name='plan/archive/detail_archive.html', model=Archive), name='detail_archive'),
    path('alert/change_date/', views.TemplateView.as_view(template_name='plan/archive/change_date_alert.html')),
    path('category/<pk>/', DetailView.as_view(template_name='plan/stat/category_detail.html', model=CostCategory)),
    path('table_input/<pk>/',
         DetailView.as_view(template_name='plan/shopping_list/table_input.html', model=ShoppingList)),
    path('tag/<name>/<tag>/', views.TagDetailView.as_view(template_name='plan/stat/tag_detail.html')),
    path('auth/', include('Auth.urls')),
    path('help/<name>/', views.GetHelpText.as_view(template_name='help.html')),

    path('ajax/create_new_plan/', actions.CreateNewPlan.as_view()),
    path('ajax/start_new_period/', actions.StartNewPeriod.as_view()),
    path('ajax/middle_icone_plan/', actions.InputMiddleIncomePlan.as_view()),
    path('ajax/delete_plan/', actions.DeletePlan.as_view()),
    path('ajax/settings_plan/', actions.SettingsPlan.as_view()),
    path('ajax/toggle_category_week_table/', actions.ToggleCategoryWeekTable.as_view()),
    path('ajax/input_cost/', actions.InputCost.as_view()),
    path('ajax/delete_cost/', actions.DeleteCost.as_view()),
    path('ajax/new_shopping_list/', actions.CreateShoppingList.as_view()),
    path('ajax/delete_item_shopping_list/<id>/', actions.DeleteItem.as_view(model=ShoppingListItem)),
    path('ajax/delete_shopping_list/<id>/', actions.DeleteItem.as_view(model=ShoppingList)),
    path('ajax/input_cost_shopping_list/<id>/', actions.InputCostShoppingList.as_view()),
    path('ajax/add_money/', actions.AddIncome.as_view()),
    path('ajax/take_money/', actions.TakeIncome.as_view()),
    path('ajax/first_log_in/', actions.first_log_in_trigger),
    path('ajax/look_last_version/', actions.look_last_version),
    path('ajax/change_tags/', actions.ChangeTags.as_view()),
    path('ajax/get-preloaded-costs/', actions.GetPreloadedCosts.as_view())
]

Money/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

Core/models.py
from datetime import datetime

from django.db import models
from django.urls import reverse


class ShoppingListItem(models.Model):
    flag = models.BooleanField('Куплено, или нет', default=False)
    name = models.CharField('Название продукта', max_length=100)
    price = models.IntegerField('Цена продукта', blank=True, null=True)
    count = models.IntegerField('Количество', default=1)
    category = models.ForeignKey('CostCategory', verbose_name='Категория', on_delete=models.CASCADE, blank=True, null=True)
    datetime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Итем шоп-листа'
        verbose_name_plural = 'Итемы шоп-листа'


class ShoppingList(models.Model):
    name = models.CharField('Название шоп-листа', max_length=100)
    item = models.ManyToManyField(ShoppingListItem, verbose_name='Итемы шоп-листа', blank=True)

    def __str__(self):
        try:
            title = '%s: %s' % (self.configuration.first().settings.first().user, self.name)
        except:
            title = '---'
        return title

    class Meta:
        verbose_name = 'Шоп-лист'
        verbose_name_plural = 'Шоп-листы'


class Tags(models.Model):

    name = models.CharField('Название метки', max_length=100)
    user = models.CharField('Пользователь', max_length=100)
    datetime = models.DateTimeField('Время и дата', auto_now=True)

    def __str__(self):
        return '%s: %s' % (self.user, self.name)

    class Meta:
        verbose_name = 'Метка'
        verbose_name_plural = 'Метки'


class History(models.Model):
    description = models.CharField('Описание действия', max_length=300, blank=True)
    datetime = models.DateTimeField('Время и дата', auto_now=True)

    def __str__(self):
        title = '---'
        if self.settings.count():
            title = '%s, %s' % (self.settings.first().user, self.datetime.date())
        return title

    class Meta:
        verbose_name = 'История аккаунта'
        verbose_name_plural = 'Истории аккаунтов'


class Cost(models.Model):

    value = models.IntegerField()
    tags = models.ManyToManyField(Tags, verbose_name='Метки')
    detailed_comment = models.CharField('Подробный комментарий', max_length=100)
    datetime = models.DateTimeField('Время и дата', auto_now=True)

    def __str__(self):
        try:
            name = self.category.first().configuration.first().settings.first().user
            title = '%s: %s' % (name, self.detailed_comment)
        except:
            title = '--'

        return title

    class Meta:
        verbose_name = 'Трата'
        verbose_name_plural = 'Траты'


class Archive(models.Model):

    date_one = models.DateField()
    date_two = models.DateField('Дата ввода', default=datetime.now)
    archive_costs = models.ManyToManyField(Cost, verbose_name='Траты', blank=True)
    spent = models.IntegerField('Потрачено', blank=True, null=True)
    saved = models.IntegerField('Сэкономлено', blank=True, null=True)
    income = models.IntegerField('Всего', blank=True, null=True)

    def get_absolute_url(self):
        return reverse('detail_archive', args=[str(self.pk)])

    def __str__(self):
        return 'План: %s' % (self.configuration.first().name if self.configuration.first().settings.count() else '---')

    class Meta:
        verbose_name = 'Архив'
        verbose_name_plural = 'Архив'


class CostCategory(models.Model):

    name = models.CharField('Название', max_length=100)
    cost = models.ManyToManyField(Cost, related_name='category', verbose_name='Траты', blank=True)
    included_week_table = models.BooleanField('Включение в недельную таблицу', default=True)
    max = models.IntegerField('Предел затраты')

    def __str__(self):
        try:
            username = self.configuration.first().settings.first().user
            configuration_name = self.configuration.first().name
            title = '{Имя: %s}, {План: %s}, {Категория: %s}' % (username, configuration_name, self.name)
        except:
            title = '---'

        return title

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Configuration(models.Model):

    name = models.CharField('Название конфигурации', max_length=100)
    category = models.ManyToManyField(CostCategory, related_name='configuration', verbose_name='Категории')
    income = models.IntegerField('Деньги в обороте')
    icon = models.CharField('Иконка на главной', max_length=100)
    color = models.CharField('Цвет иконки', max_length=20)
    history = models.ManyToManyField(History, related_name='plan_history', blank=True)
    archive = models.ManyToManyField(Archive, related_name='configuration', blank=True)
    shopping_list = models.ManyToManyField(ShoppingList, related_name='configuration', verbose_name='Списки покупок', blank=True)
    date = models.DateField('Дата ввода', default=datetime.now)

    def get_absolute_url(self):
        # для обработки null конфигурации (с пустым названием)
        name = self.name if self.name else 'none'
        return reverse('base', args=[name])

    def __str__(self):
        name = self.settings.first().user.username if self.settings.count() else '--'
        return '%s: %s' % (name, self.name)

    class Meta:
        verbose_name = 'План распределения бюджета'
        verbose_name_plural = 'Планы распределения бюджета'


class Settings(models.Model):

    configurations = models.ManyToManyField(Configuration, related_name='settings', verbose_name='Конфигурация')
    free_money = models.IntegerField('Свободные деньги', default=0)
    history = models.ManyToManyField(History, related_name='settings', blank=True)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'Пользовательская настройка'
        verbose_name_plural = 'Пользовательские настройки'


class HelpText(models.Model):
    position = models.CharField('Позиция', max_length=100)
    text = models.TextField('Пояснительный текст')

    def __str__(self):
        return self.position

    class Meta:
        verbose_name = 'Информационная система'
        verbose_name_plural = 'Информационная система'


class VersionControl(models.Model):
    version = models.CharField('Наименование версии', max_length=20)
    description = models.TextField('Описание изменений')
    date = models.DateField('Дата', auto_now_add=True)

    def __str__(self):
        return self.version

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Список версий'

Core/templates/conf/cost.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block scripts %}
    <script src="{% static 'js/cost.js' %}"></script>
{% endblock %}
{% block content %}
    <h3>Ввод траты</h3>
    <hr>
    <div class="row">
        <div class="col-lg-6">
            <form name="cost" method="POST">{% csrf_token %}
                <div style="margin-bottom: 10px">
                    <h4 style="color: #707070"><i class="fa fa-tags" aria-hidden="true"></i> Метки траты:</h4>
                    <p style="color: #b2b2b2; font-size: 13px">Для статистики используются "метки траты". Введите слово, нажмите пробел, метка зафиксируется. </p>
                    <div id="boxTags">
                        <input type="hidden" id="hiddenTags"/>
                        <ul class="ulTags" style="clear:both;">
                            <li id="newTagInput"><input class="input-tags" type="text" id="inputTag"/></li>
                        </ul>
                        <div style="clear:both;"></div>
                    </div>
                    <div class="ulTags" style="min-width: calc(100% - 88px);display: inline-block; margin-top: 10px">
                        <div style="white-space: nowrap;">
                            {% for tag in tags %}
                                <span href="javascript://" class="a_tag li_tags last_tag">{{ tag.name }}</span>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <h4 style="color: #707070"><i class="fa fa-shopping-cart" aria-hidden="true"></i> Промежуточная таблица:</h4>
                <p style="color: #b2b2b2; font-size: 13px">Выберете категорию и введите свою трату. Вы можете написать к ней комментарий. Не забудьте сохранить ваш ввод, нажав на кнопку "Записать расходы"</p>
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                    <tr>
                        <th>Категория</th>
                        <th style="text-align: center">Ввод</th>
                        <th style="text-align: center">Итог</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for category in configuration.category.all %}
                        <tr>
                            <td>{{ category.name }}</td>
                            <td class="td-cost">
                                <button class="button-input-cost btn btn-default" id="{{ category.id }}" name="{{ category.name }}" type="button">Внести</button>
                            </td>
                            <td style="text-align: center" class="td-amount">
                                <div style="font-size: 20px">
                                    <span class="cost-amount">0</span>
                                    <i style="display: none; cursor: pointer" class="fa fa-caret-down caret-hide" aria-hidden="true"></i>
                                </div>
                                <div class="hide-detail">
                                    <table style="margin: 0" class="table table-bordered">
                                        <tbody class="table-cost">
                                        </tbody>
                                    </table>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    <tr style="font-weight: bold">
                        <td colspan="2">Общая сумма:</td>
                        <td style="font-size: 20px;text-align: center">
                            <span id="cost-amount">0</span>
                        </td>
                    </tr>
                    </tbody>
                </table>
                <button class="btn btn-default" id="submit-cost" style="font-size: 18px;margin-bottom: 50px;" type="button">Записать расходы</button>
            </form>
        </div>

        <div class="col-lg-6">
            <h4 style="color: #707070"><i class="fa fa-clock-o" aria-hidden="true"></i> Последние действия:</h4>
            <p style="color: #b2b2b2; font-size: 13px">Последние действия при вводе трат. При необходимости, вы можете отменить определенную трату, нажав на нужную вам строку таблицы.</p>
            <table style="font-size: 16px" class="table table-hover">
                <thead>
                <tr style="font-weight: bold">
                    <td>Категория</td>
                    <td>Сумма</td>
                    <td width="150">Комментарий и теги</td>
                </tr>
                </thead>
                <tbody>
                {% if costs %}
                    {% for cost in costs %}
                        <tr id="{{ cost.id }}" class="action-cost" style="cursor: pointer">
                            <td>
                                {% with cost.costcategory_set.all|first as category %}
                                    <b>{{ category.name }}</b>
                                {% endwith %}
                            </td>
                            <td>
                                {{ cost.value }} р.
                            </td>
                            <td>
                                {{ cost.detailed_comment }}<br><br>
                                {% for tag in cost.tags.all %}
                                    <span class="tags-in-action">{{ tag.name }}</span>
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="3">
                            Покупок пока не было
                        </td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

Core/templates/conf/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block scripts %}
    <script src="{% static 'js/home.js' %}"></script>
{% endblock %}
{% block content %}
    <div class="row">
        <h3>Навигация</h3>
        <hr>

        <div onclick="location.href='{% url 'cost' name_url=configuration.name_url %}'" style="margin-bottom: 20px" class="col-lg-4 navigation">
            <div style="background: linear-gradient(45deg, {{ configuration.color }}, #f4d0b2);" class="block-conf">
                <h2><i class="fa fa-plus fa-4x" aria-hidden="true"></i> <br>
                    Ввести трату</h2>
            </div>
        </div>
        <div onclick="location.href='{% url 'stat' name_url=configuration.name_url %}'" style="margin-bottom: 20px" class="col-lg-4 navigation">
            <div style="background: linear-gradient(45deg, {{ configuration.color }}, #f4d0b2);" class="block-conf">
                <h2><i class="fa fa-line-chart fa-4x" aria-hidden="true"></i> <br>
                    Статистика</h2>
            </div>
        </div>
        <div onclick="location.href='{% url 'settings' name_url=configuration.name_url %}'" style="margin-bottom: 20px" class="col-lg-4 navigation">
            <div style="background: linear-gradient(45deg, {{ configuration.color }}, #f4d0b2);" class="block-conf">
                <h2><i class="fa fa-cog fa-4x" aria-hidden="true"></i> <br>
                    Настройки</h2>
            </div>
        </div>
    </div>
    <div class="row">
        <h3>Управление</h3>
        <hr>
        <div class="col-lg-4">
            <div class="manage-block">
                <h4 id="manage-block-title-1"><i class="icon fa fa-chevron-right" aria-hidden="true"></i><i class="icon fa fa-chevron-right" aria-hidden="true"></i> Новый рассчетный период</h4>
                <div style="margin-bottom: 10px;" class="input-group">
                    <input value="{{ configuration.income }}" class="form-control" style="height:50px;font-size:20px;width: 210px" type="number">
                    <button id="income" style="height: 50px;font-size: 25px" class="btn btn-default">
                        <i class="fa fa-check" style="color: #5cb85c" aria-hidden="true"></i>
                    </button>
                </div>
                <p style="color: gray; font-size: 13px">При начале нового рассчетного периода: <br>
                    - обнулятся текущие траты <br>
                    - неиспользованная сумма перейдет на ваш накопительный счет <br>
                    - отсчет месяца пойдет с сегодняшнего дня <br>
                    - <b>в случае ввода другой суммы, максимумы в категориях будут пропорционально рассчитаны автоматически. Вы всегда можете подкорректировать их в настройках.</b><br>
                    - вся история трат переместится в <a href="">архив</a>. <br>
                    По умолчанию стоит ранее введеная вами сумма. <br>
                </p>
                <p style="color: rgba(191,101,84,0.99); font-size: 13px">
                    ВНИМАНИЕ! После ввода дохода, возвратиться к прежнему состоянию плана будет невозможно.
                </p>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="manage-block">
                <h4><i class="icon fa fa-chevron-right" aria-hidden="true"></i><i class="icon fa fa-chevron-right" aria-hidden="true"></i> Изменение даты</h4>
                <div style="margin-bottom: 10px;" class="input-group">
                    <input class="form-control" value="{{ configuration.date|date:"Y-m-d" }}" style="height:50px;font-size:20px;width: 210px" type="date">
                    <button id="date" style="height: 50px;font-size: 25px" class="btn btn-default">
                        <i class="fa fa-check" style="color: #5cb85c" aria-hidden="true"></i>
                    </button>
                </div>
                <p style="color: gray; font-size: 13px">
                    Если после ввода дохода вы ошиблись днем, вы можете поменять текущую дату не создавая новый план. По умолчанию стоит текущая дата вашего плана распределения бюджета.
                </p>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="manage-block">
                <h4><i class="icon fa fa-chevron-right" aria-hidden="true"></i><i class="icon fa fa-chevron-right" aria-hidden="true"></i> Удаление плана</h4>
                <p style="color: gray; font-size: 13px">
                    После удаления неиспользованные средства перейдут на ваш накопительный счет. Восстановить план будет невозможно.
                </p>
                <button id="delete" type="button" class="btn btn-r">Удалить план "{{ configuration.name }}"</button>
            </div>
        </div>
    </div>

{% endblock %}

Core/templates/conf/settings.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block scripts %}
    <script src="{% static 'js/new.js' %}"></script>
{% endblock %}
{% block content %}
    <h3>Настройки и редактирование текущего плана</h3>
    <hr>
    <form name="new" method="POST">{% csrf_token %}
        <div class="col-lg-6">
            <h4><i class="icon fa fa-chevron-right" aria-hidden="true"></i><i class="icon fa fa-chevron-right" aria-hidden="true"></i> Название вашего плана:</h4>
            <div class="input-group">
                <span style="width: 40px" class="input-group-addon"><i class="fa fa-window-maximize" aria-hidden="true"></i></span>
                <input style="width: 140%" name="name" id="name-input" type="text" class="form-control" value="{{ configuration.name }}" placeholder="Пример: Семья"/>
            </div>
            <h4><i class="icon fa fa-chevron-right" aria-hidden="true"></i><i class="icon fa fa-chevron-right" aria-hidden="true"></i> Иконка и цвет:</h4>
            <p style="font-size: 13px; color: grey">Выбери иконку в качестве "лого" конфигурации:</p>
            <input name="icon" hidden type="text" value="{{ configuration.icon }}">
            <div id="table-icon" style="margin-bottom: 10px" class="container-fluid">
                <div class="icons lg">
                    <i style="font-size: 50px;padding-bottom: 10px" class="fa fa-cogs" aria-hidden="true"></i>
                </div>
                <div class="icons lg">
                    <i style="font-size: 50px;padding-bottom: 10px" class="fa fa-user-o" aria-hidden="true"></i>
                </div>
                <div class="icons lg">
                    <i style="font-size: 50px;padding-bottom: 10px" class="fa fa-ravelry" aria-hidden="true"></i>
                </div>
                <div class="icons lg">
                    <i style="font-size: 50px;padding-bottom: 10px" class="fa fa-eercast" aria-hidden="true"></i>
                </div>
                <div class="icons lg">
                    <i style="font-size: 50px;padding-bottom: 10px" class="fa fa-at" aria-hidden="true"></i>
                </div>
                <div class="icons lg">
                    <i style="font-size: 50px;padding-bottom: 10px" class="fa fa-bolt" aria-hidden="true"></i>
                </div>
                <div class="icons lg">
                    <i style="font-size: 50px;padding-bottom: 10px" class="fa fa-check" aria-hidden="true"></i>
                </div>
                <div class="icons lg">
                    <i style="font-size: 50px;padding-bottom: 10px" class="fa fa-sun-o" aria-hidden="true"></i>
                </div>
                <div class="icons lg">
                    <i style="font-size: 50px;padding-bottom: 10px" class="fa fa-credit-card" aria-hidden="true"></i>
                </div>
                <div class="icons lg">
                    <i style="font-size: 50px;padding-bottom: 10px" class="fa fa-money" aria-hidden="true"></i>
                </div>
                <div class="icons lg">
                    <i style="font-size: 50px;padding-bottom: 10px" class="fa fa-rub" aria-hidden="true"></i>
                </div>
                <div class="icons lg">
                    <i style="font-size: 50px;padding-bottom: 10px" class="fa fa-asterisk" aria-hidden="true"></i>
                </div>
            </div>
            <p style="font-size: 13px; color: grey">Выбери цвет стилизации:</p>
            <input value="{{ configuration.color }}" style="height: 30px; width: 60px" name="color" type="color">
            {#            <p style="margin-bottom: 40px"><select class="form-control" style="width: 150px" name="color">#}
            {#                <option selected value="black" style="background-color: black; color: black;">Черный</option>#}
            {#                <option value="red" style="background-color: red; color: red;">Красный</option>#}
            {#                <option value="blue" style="background-color: blue; color: blue;">Синий</option>#}
            {#                <option value="yellow" style="background-color: yellow; color: yellow;">Желтый</option>#}
            {#                <option value="blueviolet" style="background-color: blueviolet; color: blueviolet;">Фиолетовый</option>#}
            {#                <option value="darkorange" style="background-color: darkorange; color: darkorange;">Оранжевый</option>#}
            {#                <option value="green" style="background-color: green; color: green;">Зеленый</option>#}
            {#            </select></p>#}
        </div>
        <div class="col-lg-6">
            <h4><i class="icon fa fa-chevron-right" aria-hidden="true"></i><i class="icon fa fa-chevron-right" aria-hidden="true"></i> Распределяемая сумма:</h4>
            <div class="input-group">
                <span style="width: 40px" class="input-group-addon"><i class="fa fa-rub" aria-hidden="true"></i></span>
                <input value="{{ configuration.income }}" style="width: 140%" name="income" type="number" class="form-control" placeholder="Пример: 100000"/>
            </div>
            <h4><i class="icon fa fa-chevron-right" aria-hidden="true"></i><i class="icon fa fa-chevron-right" aria-hidden="true"></i> Редактирование категорий:</h4>
            <p style="color: grey; font-size: 13px">Редактировать можно только название и значение максимума категории. Добавлять или удалять категории нельзя.</p>
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Название</th>
                    <th width="200">Максимум</th>
                    <th style="min-width: 100px">Процент</th>
                </tr>
                </thead>
                <tbody>
                {% for category in configuration.category.all %}
                <tr>
                    <td><b>{{ forloop.counter0 }}</b></td>
                    <td><input name="name-cat{{ forloop.counter }}" type="text" class="form-control ca" value="{{ category.name }}" placeholder="Пример: На еду"/></td>
                    <td><input name="income1{{ forloop.counter }}" type="number" class="form-control cat" value="{{ category.max }}"/></td>
                    <td style="text-align: center"><span>-- </span>%</td>
                </tr>
                {% endfor %}
                <tr style="font-weight: bold" id="total-tr">
                    <td><i class="fa fa-info-circle" style="color: #261bb8;opacity: 0.8;" aria-hidden="true"></i></td>
                    <td>Остаток:</td>
                    <td><span id="o">--</span></td>
                    <td style="text-align: center"><span id="p">-- </span>% </td>
                </tr>
                </tbody>
            </table>
            <button type="submit" class="btn">Сохранить</button> <span style="color: red" id="error-form"></span>
        </div>
    </form>
{% endblock %}