Auth/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from Auth import views

urlpatterns = [
    path('register/', views.RegisterFormView.as_view()),
    path('login/', auth_views.LoginView.as_view(template_name='login.html', redirect_authenticated_user=True),
         name='user_login'),
    path('logout/', auth_views.LogoutView.as_view())
]

Core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import DetailView, ListView, RedirectView

from Core.models import Archive, CostCategory, HelpText, ShoppingList, ShoppingListItem, VersionControl
from Core.views import actions, views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_tools/', include('admin_tools.urls')),
    path('', RedirectView.as_view(url='/panel/')),
    path('favicon.ico', RedirectView.as_view(url='/static/image/favicon.ico'), name='favicon'),
    path('panel/', views.BaseTemplateView.as_view(template_name='panel/base.html'), name='panel'),
    path('panel/home/', views.BaseTemplateView.as_view(template_name='panel/panel.html')),
    path('panel/new/', views.BaseTemplateView.as_view(template_name='panel/new.html')),
    path('panel/about/', views.TemplateView.as_view(template_name='panel/about.html')),
    path('panel/help/', ListView.as_view(template_name='panel/help.html', model=HelpText)),
    path('panel/version/', ListView.as_view(template_name='panel/version.html', model=VersionControl)),
    path('panel/new_version/', ListView.as_view(template_name='panel/version.html', model=VersionControl)),
    path('panel/archive/', views.ArchiveTemplateView.as_view(template_name='panel/archive/archive.html')),
    path('<name>/', views.BaseTemplatePlanView.as_view(template_name='plan/base.html'), name='base'),
    path('<name>/home/', views.BaseTemplatePlanView.as_view(template_name='plan/home.html')),
    path('<name>/cost/', views.CostTemplatePlanView.as_view(template_name='plan/cost.html')),
    path('<name>/stat/', views.StatTemplatePlanView.as_view(template_name='plan/stat/stat.html')),
    path('<name>/shopping_list/',
         views.ShoppingListTemplateView.as_view(template_name='plan/shopping_list/shopping_list.html')),
    path('<name>/shopping_list/<id>/',
         views.DetailShoppingListTemplateView.as_view(template_name='plan/shopping_list/create_shopping_list.html')),
    path('<name>/settings/', views.BaseTemplatePlanView.as_view(template_name='plan/settings.html')),
    path('<name>/archive/', views.ArchiveTemplatePlanView.as_view(template_name='plan/archive/archive.html')),
    path('<name>/archive/<date_one>/<date_two>/',
         views.ArchiveReportLastPeriodView.as_view(template_name='plan/archive/report_last_period.html')),
    path('<name>/archive/<type_date>/', views.GetDatesInArchive.as_view()),
    path('archive/detail/<int:pk>/',
         DetailView.as_view(template_name='plan/archive/detail_archive.html', model=Archive), name='detail_archive'),
    path('alert/change_date/', views.TemplateView.as_view(template_name='plan/archive/change_date_alert.html')),
    path('category/<pk>/', DetailView.as_view(template_name='plan/stat/category_detail.html', model=CostCategory)),
    path('table_input/<pk>/',
         DetailView.as_view(template_name='plan/shopping_list/table_input.html', model=ShoppingList)),
    path('tag/<name>/<tag>/', views.TagDetailView.as_view(template_name='plan/stat/tag_detail.html')),
    path('auth/', include('Auth.urls')),
    path('help/<name>/', views.GetHelpText.as_view(template_name='help.html')),

    path('ajax/create_new_plan/', actions.CreateNewPlan.as_view()),
    path('ajax/start_new_period/', actions.StartNewPeriod.as_view()),
    path('ajax/middle_icone_plan/', actions.InputMiddleIncomePlan.as_view()),
    path('ajax/delete_plan/', actions.DeletePlan.as_view()),
    path('ajax/settings_plan/', actions.SettingsPlan.as_view()),
    path('ajax/toggle_category_week_table/', actions.ToggleCategoryWeekTable.as_view()),
    path('ajax/input_cost/', actions.InputCost.as_view()),
    path('ajax/delete_cost/', actions.DeleteCost.as_view()),
    path('ajax/new_shopping_list/', actions.CreateShoppingList.as_view()),
    path('ajax/delete_item_shopping_list/<id>/', actions.DeleteItem.as_view(model=ShoppingListItem)),
    path('ajax/delete_shopping_list/<id>/', actions.DeleteItem.as_view(model=ShoppingList)),
    path('ajax/input_cost_shopping_list/<id>/', actions.InputCostShoppingList.as_view()),
    path('ajax/add_money/', actions.AddIncome.as_view()),
    path('ajax/take_money/', actions.TakeIncome.as_view()),
    path('ajax/first_log_in/', actions.first_log_in_trigger),
    path('ajax/look_last_version/', actions.look_last_version),
    path('ajax/change_tags/', actions.ChangeTags.as_view()),
    path('ajax/get-preloaded-costs/', actions.GetPreloadedCosts.as_view())
]

Money/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

Core/models.py
from datetime import datetime

from django.db import models
from django.urls import reverse


class ShoppingListItem(models.Model):
    flag = models.BooleanField('Куплено, или нет', default=False)
    name = models.CharField('Название продукта', max_length=100)
    price = models.IntegerField('Цена продукта', blank=True, null=True)
    count = models.IntegerField('Количество', default=1)
    category = models.ForeignKey('CostCategory', verbose_name='Категория', on_delete=models.CASCADE, blank=True, null=True)
    datetime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Итем шоп-листа'
        verbose_name_plural = 'Итемы шоп-листа'


class ShoppingList(models.Model):
    name = models.CharField('Название шоп-листа', max_length=100)
    item = models.ManyToManyField(ShoppingListItem, verbose_name='Итемы шоп-листа', blank=True)

    def __str__(self):
        try:
            title = '%s: %s' % (self.configuration.first().settings.first().user, self.name)
        except:
            title = '---'
        return title

    class Meta:
        verbose_name = 'Шоп-лист'
        verbose_name_plural = 'Шоп-листы'


class Tags(models.Model):

    name = models.CharField('Название метки', max_length=100)
    user = models.CharField('Пользователь', max_length=100)
    datetime = models.DateTimeField('Время и дата', auto_now=True)

    def __str__(self):
        return '%s: %s' % (self.user, self.name)

    class Meta:
        verbose_name = 'Метка'
        verbose_name_plural = 'Метки'


class History(models.Model):
    description = models.CharField('Описание действия', max_length=300, blank=True)
    datetime = models.DateTimeField('Время и дата', auto_now=True)

    def __str__(self):
        title = '---'
        if self.settings.count():
            title = '%s, %s' % (self.settings.first().user, self.datetime.date())
        return title

    class Meta:
        verbose_name = 'История аккаунта'
        verbose_name_plural = 'Истории аккаунтов'


class Cost(models.Model):

    value = models.IntegerField()
    tags = models.ManyToManyField(Tags, verbose_name='Метки')
    detailed_comment = models.CharField('Подробный комментарий', max_length=100)
    datetime = models.DateTimeField('Время и дата', auto_now=True)

    def __str__(self):
        try:
            name = self.category.first().configuration.first().settings.first().user
            title = '%s: %s' % (name, self.detailed_comment)
        except:
            title = '--'

        return title

    class Meta:
        verbose_name = 'Трата'
        verbose_name_plural = 'Траты'


class Archive(models.Model):

    date_one = models.DateField()
    date_two = models.DateField('Дата ввода', default=datetime.now)
    archive_costs = models.ManyToManyField(Cost, verbose_name='Траты', blank=True)
    spent = models.IntegerField('Потрачено', blank=True, null=True)
    saved = models.IntegerField('Сэкономлено', blank=True, null=True)
    income = models.IntegerField('Всего', blank=True, null=True)

    def get_absolute_url(self):
        return reverse('detail_archive', args=[str(self.pk)])

    def __str__(self):
        return 'План: %s' % (self.configuration.first().name if self.configuration.first().settings.count() else '---')

    class Meta:
        verbose_name = 'Архив'
        verbose_name_plural = 'Архив'


class CostCategory(models.Model):

    name = models.CharField('Название', max_length=100)
    cost = models.ManyToManyField(Cost, related_name='category', verbose_name='Траты', blank=True)
    included_week_table = models.BooleanField('Включение в недельную таблицу', default=True)
    max = models.IntegerField('Предел затраты')

    def __str__(self):
        try:
            username = self.configuration.first().settings.first().user
            configuration_name = self.configuration.first().name
            title = '{Имя: %s}, {План: %s}, {Категория: %s}' % (username, configuration_name, self.name)
        except:
            title = '---'

        return title

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Configuration(models.Model):

    name = models.CharField('Название конфигурации', max_length=100)
    category = models.ManyToManyField(CostCategory, related_name='configuration', verbose_name='Категории')
    income = models.IntegerField('Деньги в обороте')
    icon = models.CharField('Иконка на главной', max_length=100)
    color = models.CharField('Цвет иконки', max_length=20)
    history = models.ManyToManyField(History, related_name='plan_history', blank=True)
    archive = models.ManyToManyField(Archive, related_name='configuration', blank=True)
    shopping_list = models.ManyToManyField(ShoppingList, related_name='configuration', verbose_name='Списки покупок', blank=True)
    date = models.DateField('Дата ввода', default=datetime.now)

    def get_absolute_url(self):
        # для обработки null конфигурации (с пустым названием)
        name = self.name if self.name else 'none'
        return reverse('base', args=[name])

    def __str__(self):
        name = self.settings.first().user.username if self.settings.count() else '--'
        return '%s: %s' % (name, self.name)

    class Meta:
        verbose_name = 'План распределения бюджета'
        verbose_name_plural = 'Планы распределения бюджета'


class Settings(models.Model):

    configurations = models.ManyToManyField(Configuration, related_name='settings', verbose_name='Конфигурация')
    free_money = models.IntegerField('Свободные деньги', default=0)
    history = models.ManyToManyField(History, related_name='settings', blank=True)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'Пользовательская настройка'
        verbose_name_plural = 'Пользовательские настройки'


class HelpText(models.Model):
    position = models.CharField('Позиция', max_length=100)
    text = models.TextField('Пояснительный текст')

    def __str__(self):
        return self.position

    class Meta:
        verbose_name = 'Информационная система'
        verbose_name_plural = 'Информационная система'


class VersionControl(models.Model):
    version = models.CharField('Наименование версии', max_length=20)
    description = models.TextField('Описание изменений')
    date = models.DateField('Дата', auto_now_add=True)

    def __str__(self):
        return self.version

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Список версий'

Core/templates/plan/archive/archive.html
{% load staticfiles %}
{% load poll_extras %}
    <div class="row">
        <h3>Архивная статистика <i class="fa fa-question-circle-o help-button" aria-hidden="true"></i></h3>
        <hr>
        <div id="archive-stat">
            <div class="inner">
                <i style="font-size: 100px; color: {{ configuration.color }}" class="fa fa-spinner fa-spin fa-3x fa-fw fa-5x"></i>
            </div>
        </div>
    </div>
    <div class="row">
        <h3>Завершенные периоды и их графическая визуализация <i class="fa fa-question-circle-o help-button" aria-hidden="true"></i></h3>
        <hr>
        {% if archive %}
        <div id="chart-archive-period" style="min-height: 270px;"></div>
        {% else %}
        <b>Необходимые данные для построения графика отсутствуют</b>
        {% endif %}
        {% for item in archive %}
            <div id="{{ item.id }}" class="col-lg-4 navigation">
                <div style="background: linear-gradient(45deg, #f4d0b2, {{ configuration.color }});" class="block-conf">
                    <div style="font-size: 26px; margin-bottom: 10px">
                        с <b>{{ item.date_one }}</b> по <br>
                        <b>{{ item.date_two }}</b>
                    </div>
                    <div style="font-size: 23px">
                        <span style="color: #ff544b;">Потрачено: {{ item.spent|points }} </span> <i class="fa fa-rub" aria-hidden="true"></i>
                        <br>
                        <span style="color: #00b500;">Сохранено: {{ item.saved|points }}</span> <i class="fa fa-rub" aria-hidden="true"></i>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
<script>
    new Morris.Line({
        element: 'chart-archive-period',
        data: [

            {% for item in archive %}
                {name: '{{ item.date_two|date:"Y-m-d" }}', income: {{ item.income }}, spent: {{ item.spent }}},
            {% endfor %}
        ],
        xkey: 'name',
        ykeys: ['income', 'spent'],
        lineColors: ['#0d09da','#d60400'],
        labels: ['Общая сумма', 'Потрачено'],
        pointFillColors: ['{{ configuration.color }}', '{{ configuration.color }}'],
        pointStrokeColors: ['#000', '#000'],
        ymin: 'auto',
        lineWidth: '1',
        postUnits: ' р.',
        xLabels: 'month',
        resize: true

    });
</script>
<script src="{% static 'js/archive.js' %}"></script>

Core/templates/plan/archive/change_date_alert.html
<p><b>Первая дата:</b></p>
<input style="max-width: 200px;display: inline-block" name="name-plan" id="date-one" type="date" class="form-control"/>
<p style="padding-top: 5px"><b>Вторая дата:</b></p>
<input style="max-width: 200px;display: inline-block" name="name-plan" id="date-two" type="date" class="form-control"/>
<div class="help-dates" style="margin-bottom: 15px">
    <span id="time-all">за все время</span> <span id="time-1">за 1 месяц</span>
    <span id="time-3">за 3 месяца</span> <span id="time-6">за полгода</span>
    <span id="time-12">за год</span> <br>
</div>
<script>
    function get_and_change_dates(id) {
        var plan = location.pathname;
        $.post(plan + 'archive/' + id + '/', function (data) {
            $('#date-one').val(data.date_one);
            $('#date-two').val(data.date_two);
        })
    }
    $('.help-dates').on('click', function (e) {
        var id = e.target.id;
        get_and_change_dates(id)
    });
</script>

Core/templates/plan/archive/detail_archive.html
{% load poll_extras %}
<div style="font-size: 17px; text-align: left">
    <p><b>Общая сумма: <span style="color:blue">{{ object.income|points }}</span> р.</b></p>
    <p><b>Потрачено: <span style="color: red">{{ object.spent|points }}</span> р.</b></p>
    <p><b>Сохранено: <span style="color: green">{{ object.saved|points }}</span> р.</b></p>
    <p><b>Все траты:</b></p>
</div>
{% with object.archive_costs.all as objects %}
    {% include 'table_detail_cost.html' %}
{% endwith %}

Core/templates/plan/archive/report_last_period.html
{% load poll_extras %}
<div style="margin-bottom: 50px" class="col-lg-6">
    <h4> Интервал: <b>{{ date_one }} / {{ date_two }}</b> (<b>{{ days }}</b>&nbsp;дн.)</h4>
    <button class="btn btn-default" id="edit-interval" style="font-size: 18px;margin-bottom: 40px;" type="button">Изменить интервал</button>
    <h4>
        <b><i class="fa fa-info-circle" style="opacity: 0.8;" aria-hidden="true"></i></b> Краткая статистика
    </h4>
    <p class="info-archive"><i class="fa fa-caret-right" style="color:{{ configuration.color }}" aria-hidden="true"></i> было потрачено <b>{{ spent|points }}</b> р.</p>
    <p class="info-archive"><i class="fa fa-caret-right" style="color:{{ configuration.color }}" aria-hidden="true"></i> средняя трата за день <b>{{ middle_cost|points }}</b> р.</p>
    <p class="info-archive"><i class="fa fa-caret-right" style="color:{{ configuration.color }}" aria-hidden="true"></i> самая большая трата <b>{{ biggest_cost|first|points }}</b> р. с комментарием: <b>{{ biggest_cost|last }}</b></p>
    <h4 style="margin-top: 50px">
        <b>#</b> Статистика трат по меткам:
    </h4>
    {% if dict_tags %}
        <table class="table">
            <thead>
            <tr style="font-weight: bold">
                <td>Метка</td>
                <td style="text-align: center"><i class="fa fa-rub" aria-hidden="true"></i></td>
            </tr>
            </thead>
            <tbody>
            {% for name, value in dict_tags %}
                <tr>
                    <td class="tags-view-archive" id="{{ name }}">
                        {{ name }}
                    </td>
                    <td class="tags-value" style="width: 80px; border-left: 1px solid #d0d0d0; text-align: center">
                        {{ value|points }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <b>За этот период трат не нашлось</b>
    {% endif %}
</div>
<div style="margin-bottom: 50px" class="col-lg-6">
    <h4>
        <b><i class="fa fa-list-ul" aria-hidden="true"></i></b> Траты, попавшие в выбранный интервал:
    </h4>
    <div class="wrapper-history">
        {% if archive_costs %}
            <table class="table">
                <tbody style="font-size: 15px">
                {% for cost in archive_costs %}
                    <tr>
                        <td>
                            <b>{{ cost.datetime }}</b><br>
                            Покупка на сумму: <b>{{ cost.value|points }} <i class="fa fa-rub" aria-hidden="true"></i></b>.
                            <br>
                            Комментарий: <b>{{ cost.detailed_comment }}</b><br>
                            {% for tag in cost.tags.all %}<span class="tags-in-action">{{ tag.name }}</span>{% endfor %}
                            <br>
                            {% if cost.category.all %}
                                {% with cost.category.all.first.configuration.all.first as conf %}
                                    <span style="opacity: 0.7;  font-size: 14px;"><b style="color: {{ conf.color }}">{{ conf.name }}</b> (текущая)</span>
                                {% endwith %}
                            {% endif %}
                            {% if cost.archive_set.all %}
                                {% with cost.archive_set.all.first.configuration.all.first as conf %}
                                    <span style="opacity: 0.7; font-size: 14px;">
                                        {% if conf.name %}
                                            <b style="color: {{ conf.color }}">{{ conf.name }}</b> (архивная)
                                        {% else %}
                                            Изымание средств
                                        {% endif %}
                                    </span>
                                {% endwith %}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <b>За этот период трат не нашлось</b>
        {% endif %}
    </div>
</div>